import Header from "@/components/pages/main/header";
import Footer from "@/components/pages/unauth/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-background flex flex-col min-h-screen">
      <Header />
      <div className="flex-1 overflow-x-hidden">{children}</div>
      <Footer />
    </div>
  );
}
