import Header from "@/components/pages/main/header";
import Footer from "@/components/pages/unauth/footer";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("token")?.value;
  const refreshToken = cookieStore.get("refresh_token")?.value;

  if (!accessToken || !refreshToken) {
    redirect("/login");
  }

  return (
    <div className="bg-background flex flex-col min-h-screen">
      <Header />
      <div className="flex-1 overflow-x-hidden">{children}</div>
      <Footer />
    </div>
  );
}
