import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { verifyAccessToken, verifyRefreshToken } from "@/utils/jwt";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("token")?.value;
  const refreshToken = cookieStore.get("refresh_token")?.value;

  if (accessToken && refreshToken) {
    try {
      verifyAccessToken(accessToken || "");
    } catch {
      try {
        if (refreshToken) {
          verifyRefreshToken(refreshToken || "");
        }
      } catch {
        cookieStore.delete("token");
        cookieStore.delete("refresh_token");
      }
    }
  }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
