import Sidebar from "@/components/pages/admin/sidebar";
import Header from "@/components/pages/main/header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={cn("bg-background flex min-h-screen", "max-lg:flex-col")}>
      <Sidebar className="max-lg:hidden" />
      <Header forceEditMode className="hidden max-lg:flex" />

      <div className="flex-1 overflow-x-hidden">{children}</div>
    </div>
  );
}
